//
// AccessRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccessRule: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var priority: Int?
    public var container: String?
    public var transform: String?
    public var permissions: [String]?

    public init(description: String? = nil, priority: Int? = nil, container: String? = nil, transform: String? = nil, permissions: [String]? = nil) {
        self.description = description
        self.priority = priority
        self.container = container
        self.transform = transform
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case priority
        case container
        case transform
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(container, forKey: .container)
        try container.encodeIfPresent(transform, forKey: .transform)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }
}

