//
// AdditionalCardDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AdditionalCardDetails: Codable, JSONEncodable, Hashable {

    public var brand: String?
    public var funding: String?
    public var authentication: String?
    public var issuer: CardIssuer?

    public init(brand: String? = nil, funding: String? = nil, authentication: String? = nil, issuer: CardIssuer? = nil) {
        self.brand = brand
        self.funding = funding
        self.authentication = authentication
        self.issuer = issuer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brand
        case funding
        case authentication
        case issuer
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(brand, forKey: .brand)
        try containerEncoder.encodeIfPresent(funding, forKey: .funding)
        try containerEncoder.encodeIfPresent(authentication, forKey: .authentication)
        try containerEncoder.encodeIfPresent(issuer, forKey: .issuer)
    }
}

