//
// ApplePayTokenizeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApplePayTokenizeResponse: Codable, JSONEncodable, Hashable {

    public var tokenIntent: CreateTokenIntentResponse?

    public init(tokenIntent: CreateTokenIntentResponse? = nil) {
        self.tokenIntent = tokenIntent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenIntent = "token_intent"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(tokenIntent, forKey: .tokenIntent)
    }
}

