//
// ApplePayTokenizeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApplePayTokenizeRequest: Codable, JSONEncodable, Hashable {

    public var applePaymentMethodToken: ApplePayMethodToken?

    public init(applePaymentMethodToken: ApplePayMethodToken? = nil) {
        self.applePaymentMethodToken = applePaymentMethodToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applePaymentMethodToken = "apple_payment_method_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(applePaymentMethodToken, forKey: .applePaymentMethodToken)
    }
}

