//
// ApplePayDomainRegistrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApplePayDomainRegistrationRequest: Codable, JSONEncodable, Hashable {

    public var domain: String

    public init(domain: String) {
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encode(domain, forKey: .domain)
    }
}

