//
// ApplePayDomainRegistrationListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApplePayDomainRegistrationListRequest: Codable, JSONEncodable, Hashable {

    public var domains: [String]?

    public init(domains: [String]? = nil) {
        self.domains = domains
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domains
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(domains, forKey: .domains)
    }
}

