//
// ApplicationKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApplicationKey: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var key: String?
    public var createdBy: UUID?
    public var createdAt: Date?

    public init(id: UUID? = nil, key: String? = nil, createdBy: UUID? = nil, createdAt: Date? = nil) {
        self.id = id
        self.key = key
        self.createdBy = createdBy
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case key
        case createdBy = "created_by"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(id, forKey: .id)
        try containerEncoder.encodeIfPresent(key, forKey: .key)
        try containerEncoder.encodeIfPresent(createdBy, forKey: .createdBy)
        try containerEncoder.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

