//
// BankVerificationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BankVerificationRequest: Codable, JSONEncodable, Hashable {

    public var tokenId: String
    public var countryCode: String?
    public var routingNumber: String?

    public init(tokenId: String, countryCode: String? = nil, routingNumber: String? = nil) {
        self.tokenId = tokenId
        self.countryCode = countryCode
        self.routingNumber = routingNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenId = "token_id"
        case countryCode = "country_code"
        case routingNumber = "routing_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encode(tokenId, forKey: .tokenId)
        try containerEncoder.encodeIfPresent(countryCode, forKey: .countryCode)
        try containerEncoder.encodeIfPresent(routingNumber, forKey: .routingNumber)
    }
}

