//
// BinDetailsProduct.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BinDetailsProduct: Codable, JSONEncodable, Hashable {

    public var code: String?
    public var name: String?

    public init(code: String? = nil, name: String? = nil) {
        self.code = code
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(code, forKey: .code)
        try containerEncoder.encodeIfPresent(name, forKey: .name)
    }
}

