//
// CardIssuerCountry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CardIssuerCountry: Codable, JSONEncodable, Hashable {

    public var alpha2: String?
    public var name: String?
    public var numeric: String?

    public init(alpha2: String? = nil, name: String? = nil, numeric: String? = nil) {
        self.alpha2 = alpha2
        self.name = name
        self.numeric = numeric
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alpha2
        case name
        case numeric
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(alpha2, forKey: .alpha2)
        try containerEncoder.encodeIfPresent(name, forKey: .name)
        try containerEncoder.encodeIfPresent(numeric, forKey: .numeric)
    }
}

