//
// CardIssuer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CardIssuer: Codable, JSONEncodable, Hashable {

    public var country: String?
    public var name: String?

    public init(country: String? = nil, name: String? = nil) {
        self.country = country
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(country, forKey: .country)
        try containerEncoder.encodeIfPresent(name, forKey: .name)
    }
}

