//
// CardholderInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CardholderInfo: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var address: Address?

    public init(name: String? = nil, address: Address? = nil) {
        self.name = name
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(name, forKey: .name)
        try containerEncoder.encodeIfPresent(address, forKey: .address)
    }
}

