//
// ClientEncryptionKeyMetadataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClientEncryptionKeyMetadataResponse: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var expiresAt: Date?

    public init(id: UUID? = nil, expiresAt: Date? = nil) {
        self.id = id
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(id, forKey: .id)
        try containerEncoder.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}

