//
// ClientEncryptionKeyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClientEncryptionKeyRequest: Codable, JSONEncodable, Hashable {

    public var expiresAt: Date?

    public init(expiresAt: Date? = nil) {
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expiresAt = "expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}

