//
// CreateNetworkTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateNetworkTokenRequest: Codable, JSONEncodable, Hashable {

    public var data: Card?
    public var tokenId: String?
    public var tokenIntentId: String?
    public var cardholderInfo: CardholderInfo?

    public init(data: Card? = nil, tokenId: String? = nil, tokenIntentId: String? = nil, cardholderInfo: CardholderInfo? = nil) {
        self.data = data
        self.tokenId = tokenId
        self.tokenIntentId = tokenIntentId
        self.cardholderInfo = cardholderInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case tokenId = "token_id"
        case tokenIntentId = "token_intent_id"
        case cardholderInfo = "cardholder_info"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(data, forKey: .data)
        try containerEncoder.encodeIfPresent(tokenId, forKey: .tokenId)
        try containerEncoder.encodeIfPresent(tokenIntentId, forKey: .tokenIntentId)
        try containerEncoder.encodeIfPresent(cardholderInfo, forKey: .cardholderInfo)
    }
}

