//
// CreateProxyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateProxyRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var destinationUrl: String
    public var requestReactorId: UUID?
    public var responseReactorId: UUID?
    public var requireAuth: Bool?

    public init(name: String, destinationUrl: String, requestReactorId: UUID? = nil, responseReactorId: UUID? = nil, requireAuth: Bool? = nil) {
        self.name = name
        self.destinationUrl = destinationUrl
        self.requestReactorId = requestReactorId
        self.responseReactorId = responseReactorId
        self.requireAuth = requireAuth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case destinationUrl = "destination_url"
        case requestReactorId = "request_reactor_id"
        case responseReactorId = "response_reactor_id"
        case requireAuth = "require_auth"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(destinationUrl, forKey: .destinationUrl)
        try container.encodeIfPresent(requestReactorId, forKey: .requestReactorId)
        try container.encodeIfPresent(responseReactorId, forKey: .responseReactorId)
        try container.encodeIfPresent(requireAuth, forKey: .requireAuth)
    }
}

