//
// CreateApplicationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateApplicationRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var type: String
    public var permissions: [String]?
    public var rules: [AccessRule]?
    public var createKey: Bool?

    public init(name: String, type: String, permissions: [String]? = nil, rules: [AccessRule]? = nil, createKey: Bool? = nil) {
        self.name = name
        self.type = type
        self.permissions = permissions
        self.rules = rules
        self.createKey = createKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case permissions
        case rules
        case createKey = "create_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encode(name, forKey: .name)
        try containerEncoder.encode(type, forKey: .type)
        try containerEncoder.encodeIfPresent(permissions, forKey: .permissions)
        try containerEncoder.encodeIfPresent(rules, forKey: .rules)
        try containerEncoder.encodeIfPresent(createKey, forKey: .createKey)
    }
}

