//
// CreateTenantConnectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateTenantConnectionRequest: Codable, JSONEncodable, Hashable {

    public var strategy: String
    public var options: TenantConnectionOptions

    public init(strategy: String, options: TenantConnectionOptions) {
        self.strategy = strategy
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case strategy
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encode(strategy, forKey: .strategy)
        try containerEncoder.encode(options, forKey: .options)
    }
}

