//
// CreateTransactionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateTransactionResponse: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var createdBy: UUID?
    public var createdAt: Date?
    public var expiresAt: Date?

    public init(id: UUID? = nil, createdBy: UUID? = nil, createdAt: Date? = nil, expiresAt: Date? = nil) {
        self.id = id
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdBy = "created_by"
        case createdAt = "created_at"
        case expiresAt = "expires_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(id, forKey: .id)
        try containerEncoder.encodeIfPresent(createdBy, forKey: .createdBy)
        try containerEncoder.encodeIfPresent(createdAt, forKey: .createdAt)
        try containerEncoder.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}

