//
// CreateDocumentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateDocumentRequest: Codable, JSONEncodable, Hashable {

    public var metadata: [String: String]?

    public init(metadata: [String: String]? = nil) {
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(metadata, forKey: .metadata)
    }
}

