//
// CreateTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateTokenResponse: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var tenantId: UUID?
    public var type: String?
    public var fingerprint: String?
    public var fingerprintExpression: String?
    public var mask: AnyCodable?
    public var data: AnyCodable?
    public var metadata: [String: String]?
    public var privacy: Privacy?
    public var searchIndexes: [String]?
    public var createdBy: UUID?
    public var createdAt: Date?
    public var modifiedBy: UUID?
    public var modifiedAt: Date?
    public var expiresAt: Date?
    public var container: String?

    public init(id: String? = nil, tenantId: UUID? = nil, type: String? = nil, fingerprint: String? = nil, fingerprintExpression: String? = nil, mask: AnyCodable? = nil, data: AnyCodable? = nil, metadata: [String: String]? = nil, privacy: Privacy? = nil, searchIndexes: [String]? = nil, createdBy: UUID? = nil, createdAt: Date? = nil, modifiedBy: UUID? = nil, modifiedAt: Date? = nil, expiresAt: Date? = nil, container: String? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.type = type
        self.fingerprint = fingerprint
        self.fingerprintExpression = fingerprintExpression
        self.mask = mask
        self.data = data
        self.metadata = metadata
        self.privacy = privacy
        self.searchIndexes = searchIndexes
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.modifiedBy = modifiedBy
        self.modifiedAt = modifiedAt
        self.expiresAt = expiresAt
        self.container = container
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case type
        case fingerprint
        case fingerprintExpression = "fingerprint_expression"
        case mask
        case data
        case metadata
        case privacy
        case searchIndexes = "search_indexes"
        case createdBy = "created_by"
        case createdAt = "created_at"
        case modifiedBy = "modified_by"
        case modifiedAt = "modified_at"
        case expiresAt = "expires_at"
        case container
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(fingerprint, forKey: .fingerprint)
        try container.encodeIfPresent(fingerprintExpression, forKey: .fingerprintExpression)
        try container.encodeIfPresent(mask, forKey: .mask)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(privacy, forKey: .privacy)
        try container.encodeIfPresent(searchIndexes, forKey: .searchIndexes)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(modifiedBy, forKey: .modifiedBy)
        try container.encodeIfPresent(modifiedAt, forKey: .modifiedAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(container, forKey: .container)
    }
}

