//
// CursorPagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CursorPagination: Codable, JSONEncodable, Hashable {

    public var pageSize: Int?
    public var next: String?

    public init(pageSize: Int? = nil, next: String? = nil) {
        self.pageSize = pageSize
        self.next = next
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pageSize = "page_size"
        case next
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(pageSize, forKey: .pageSize)
        try containerEncoder.encodeIfPresent(next, forKey: .next)
    }
}

