//
// DomainRegistrationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DomainRegistrationResponse: Codable, JSONEncodable, Hashable {

    public var domain: String?
    public var status: String?

    public init(domain: String? = nil, status: String? = nil) {
        self.domain = domain
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(domain, forKey: .domain)
        try containerEncoder.encodeIfPresent(status, forKey: .status)
    }
}

