//
// GetApplications.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetApplications: Codable, JSONEncodable, Hashable {

    public var applicationIds: [UUID]?
    public var page: Int?
    public var size: Int?

    public init(applicationIds: [UUID]? = nil, page: Int? = nil, size: Int? = nil) {
        self.applicationIds = applicationIds
        self.page = page
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applicationIds
        case page
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(applicationIds, forKey: .applicationIds)
        try containerEncoder.encodeIfPresent(page, forKey: .page)
        try containerEncoder.encodeIfPresent(size, forKey: .size)
    }
}

