//
// GetPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPermissions: Codable, JSONEncodable, Hashable {

    public var applicationType: String?

    public init(applicationType: String? = nil) {
        self.applicationType = applicationType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applicationType = "application_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(applicationType, forKey: .applicationType)
    }
}

