//
// GetReactors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetReactors: Codable, JSONEncodable, Hashable {

    public var reactorIds: [UUID]?
    public var name: String?
    public var page: Int?
    public var size: Int?

    public init(reactorIds: [UUID]? = nil, name: String? = nil, page: Int? = nil, size: Int? = nil) {
        self.reactorIds = reactorIds
        self.name = name
        self.page = page
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reactorIds
        case name
        case page
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(reactorIds, forKey: .reactorIds)
        try containerEncoder.encodeIfPresent(name, forKey: .name)
        try containerEncoder.encodeIfPresent(page, forKey: .page)
        try containerEncoder.encodeIfPresent(size, forKey: .size)
    }
}

