//
// GetReactors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetReactors: Codable, JSONEncodable, Hashable {

    public var id: [UUID]?
    public var name: String?
    public var page: Int?
    public var start: String?
    public var size: Int?

    public init(id: [UUID]? = nil, name: String? = nil, page: Int? = nil, start: String? = nil, size: Int? = nil) {
        self.id = id
        self.name = name
        self.page = page
        self.start = start
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case page
        case start
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(id, forKey: .id)
        try containerEncoder.encodeIfPresent(name, forKey: .name)
        try containerEncoder.encodeIfPresent(page, forKey: .page)
        try containerEncoder.encodeIfPresent(start, forKey: .start)
        try containerEncoder.encodeIfPresent(size, forKey: .size)
    }
}

