//
// GetReactorFormulas.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetReactorFormulas: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var page: Int?
    public var size: Int?

    public init(name: String? = nil, page: Int? = nil, size: Int? = nil) {
        self.name = name
        self.page = page
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case page
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

