//
// GetTenantMembers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTenantMembers: Codable, JSONEncodable, Hashable {

    public var userIds: [UUID]?
    public var page: Int?
    public var size: Int?

    public init(userIds: [UUID]? = nil, page: Int? = nil, size: Int? = nil) {
        self.userIds = userIds
        self.page = page
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userIds
        case page
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userIds, forKey: .userIds)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

