//
// GetTenantMembers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTenantMembers: Codable, JSONEncodable, Hashable {

    public var userId: [UUID]?
    public var page: Int?
    public var start: String?
    public var size: Int?

    public init(userId: [UUID]? = nil, page: Int? = nil, start: String? = nil, size: Int? = nil) {
        self.userId = userId
        self.page = page
        self.start = start
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case page
        case start
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(userId, forKey: .userId)
        try containerEncoder.encodeIfPresent(page, forKey: .page)
        try containerEncoder.encodeIfPresent(start, forKey: .start)
        try containerEncoder.encodeIfPresent(size, forKey: .size)
    }
}

