//
// GetTenantInvitations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTenantInvitations: Codable, JSONEncodable, Hashable {

    public var status: TenantInvitationStatus?
    public var page: Int?
    public var size: Int?

    public init(status: TenantInvitationStatus? = nil, page: Int? = nil, size: Int? = nil) {
        self.status = status
        self.page = page
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case page
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

