//
// GooglePaymentMethodToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GooglePaymentMethodToken: Codable, JSONEncodable, Hashable {

    public var protocolVersion: String?
    public var signature: String?
    public var intermediateSigningKey: IntermediateSigningKey?
    public var signedMessage: String?

    public init(protocolVersion: String? = nil, signature: String? = nil, intermediateSigningKey: IntermediateSigningKey? = nil, signedMessage: String? = nil) {
        self.protocolVersion = protocolVersion
        self.signature = signature
        self.intermediateSigningKey = intermediateSigningKey
        self.signedMessage = signedMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case protocolVersion
        case signature
        case intermediateSigningKey
        case signedMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(protocolVersion, forKey: .protocolVersion)
        try containerEncoder.encodeIfPresent(signature, forKey: .signature)
        try containerEncoder.encodeIfPresent(intermediateSigningKey, forKey: .intermediateSigningKey)
        try containerEncoder.encodeIfPresent(signedMessage, forKey: .signedMessage)
    }
}

