//
// GooglePayTokenizeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GooglePayTokenizeRequest: Codable, JSONEncodable, Hashable {

    public var googlePaymentMethodToken: GooglePaymentMethodToken?

    public init(googlePaymentMethodToken: GooglePaymentMethodToken? = nil) {
        self.googlePaymentMethodToken = googlePaymentMethodToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case googlePaymentMethodToken = "google_payment_method_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(googlePaymentMethodToken, forKey: .googlePaymentMethodToken)
    }
}

