//
// Header.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Header: Codable, JSONEncodable, Hashable {

    public var publicKeyHash: String?
    public var ephemeralPublicKey: String?
    public var transactionId: String?
    public var applicationData: String?

    public init(publicKeyHash: String? = nil, ephemeralPublicKey: String? = nil, transactionId: String? = nil, applicationData: String? = nil) {
        self.publicKeyHash = publicKeyHash
        self.ephemeralPublicKey = ephemeralPublicKey
        self.transactionId = transactionId
        self.applicationData = applicationData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publicKeyHash
        case ephemeralPublicKey
        case transactionId
        case applicationData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(publicKeyHash, forKey: .publicKeyHash)
        try containerEncoder.encodeIfPresent(ephemeralPublicKey, forKey: .ephemeralPublicKey)
        try containerEncoder.encodeIfPresent(transactionId, forKey: .transactionId)
        try containerEncoder.encodeIfPresent(applicationData, forKey: .applicationData)
    }
}

