//
// MonthlyActiveTokenHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MonthlyActiveTokenHistory: Codable, JSONEncodable, Hashable {

    public var year: Int?
    public var month: Int?
    public var count: Int64?

    public init(year: Int? = nil, month: Int? = nil, count: Int64? = nil) {
        self.year = year
        self.month = month
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case month
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(year, forKey: .year)
        try containerEncoder.encodeIfPresent(month, forKey: .month)
        try containerEncoder.encodeIfPresent(count, forKey: .count)
    }
}

