//
// NetworkTokenExtras.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NetworkTokenExtras: Codable, JSONEncodable, Hashable {

    public var deduplicated: Bool?

    public init(deduplicated: Bool? = nil) {
        self.deduplicated = deduplicated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deduplicated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(deduplicated, forKey: .deduplicated)
    }
}

