//
// NetworkTokenCryptogram.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NetworkTokenCryptogram: Codable, JSONEncodable, Hashable {

    public var cryptogram: String?
    public var eci: String?

    public init(cryptogram: String? = nil, eci: String? = nil) {
        self.cryptogram = cryptogram
        self.eci = eci
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cryptogram
        case eci
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(cryptogram, forKey: .cryptogram)
        try containerEncoder.encodeIfPresent(eci, forKey: .eci)
    }
}

