//
// PatchProxyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchProxyRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var destinationUrl: String?
    public var requestTransform: ProxyTransform?
    public var responseTransform: ProxyTransform?
    public var application: Application?
    public var configuration: [String: String]?
    public var requireAuth: Bool?

    public init(name: String? = nil, destinationUrl: String? = nil, requestTransform: ProxyTransform? = nil, responseTransform: ProxyTransform? = nil, application: Application? = nil, configuration: [String: String]? = nil, requireAuth: Bool? = nil) {
        self.name = name
        self.destinationUrl = destinationUrl
        self.requestTransform = requestTransform
        self.responseTransform = responseTransform
        self.application = application
        self.configuration = configuration
        self.requireAuth = requireAuth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case destinationUrl = "destination_url"
        case requestTransform = "request_transform"
        case responseTransform = "response_transform"
        case application
        case configuration
        case requireAuth = "require_auth"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(name, forKey: .name)
        try containerEncoder.encodeIfPresent(destinationUrl, forKey: .destinationUrl)
        try containerEncoder.encodeIfPresent(requestTransform, forKey: .requestTransform)
        try containerEncoder.encodeIfPresent(responseTransform, forKey: .responseTransform)
        try containerEncoder.encodeIfPresent(application, forKey: .application)
        try containerEncoder.encodeIfPresent(configuration, forKey: .configuration)
        try containerEncoder.encodeIfPresent(requireAuth, forKey: .requireAuth)
    }
}

