//
// PaymentData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaymentData: Codable, JSONEncodable, Hashable {

    public var data: String?
    public var signature: String?
    public var header: Header?
    public var version: String?

    public init(data: String? = nil, signature: String? = nil, header: Header? = nil, version: String? = nil) {
        self.data = data
        self.signature = signature
        self.header = header
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case signature
        case header
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(data, forKey: .data)
        try containerEncoder.encodeIfPresent(signature, forKey: .signature)
        try containerEncoder.encodeIfPresent(header, forKey: .header)
        try containerEncoder.encodeIfPresent(version, forKey: .version)
    }
}

