//
// ReactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReactRequest: Codable, JSONEncodable, Hashable {

    public var args: AnyCodable?
    public var callbackUrl: String?
    public var timeoutMs: Int?

    public init(args: AnyCodable? = nil, callbackUrl: String? = nil, timeoutMs: Int? = nil) {
        self.args = args
        self.callbackUrl = callbackUrl
        self.timeoutMs = timeoutMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case args
        case callbackUrl = "callback_url"
        case timeoutMs = "timeout_ms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(args, forKey: .args)
        try containerEncoder.encodeIfPresent(callbackUrl, forKey: .callbackUrl)
        try containerEncoder.encodeIfPresent(timeoutMs, forKey: .timeoutMs)
    }
}

