//
// ReactResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReactResponse: Codable, JSONEncodable, Hashable {

    public var tokens: JSONValue?
    public var raw: JSONValue?
    public var body: JSONValue?
    public var headers: JSONValue?

    public init(tokens: JSONValue? = nil, raw: JSONValue? = nil, body: JSONValue? = nil, headers: JSONValue? = nil) {
        self.tokens = tokens
        self.raw = raw
        self.body = body
        self.headers = headers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokens
        case raw
        case body
        case headers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(tokens, forKey: .tokens)
        try containerEncoder.encodeIfPresent(raw, forKey: .raw)
        try containerEncoder.encodeIfPresent(body, forKey: .body)
        try containerEncoder.encodeIfPresent(headers, forKey: .headers)
    }
}

