//
// ReactResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReactResponse: Codable, JSONEncodable, Hashable {

    public var tokens: AnyCodable?
    public var raw: AnyCodable?

    public init(tokens: AnyCodable? = nil, raw: AnyCodable? = nil) {
        self.tokens = tokens
        self.raw = raw
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokens
        case raw
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tokens, forKey: .tokens)
        try container.encodeIfPresent(raw, forKey: .raw)
    }
}

