//
// SearchTokensRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchTokensRequest: Codable, JSONEncodable, Hashable {

    public var query: String?
    public var page: Int?
    public var size: Int?

    public init(query: String? = nil, page: Int? = nil, size: Int? = nil) {
        self.query = query
        self.page = page
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case page
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(query, forKey: .query)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(size, forKey: .size)
    }
}

