//
// TenantInvitationStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TenantInvitationStatus: String, Sendable, Codable, CaseIterable {
    case pending = "PENDING"
    case expired = "EXPIRED"
}
