//
// TenantMemberResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TenantMemberResponse: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var tenantId: UUID?
    public var user: User?
    public var role: String?
    public var createdBy: UUID?
    public var createdDate: Date?
    public var modifiedBy: UUID?
    public var modifiedAt: Date?

    public init(id: UUID? = nil, tenantId: UUID? = nil, user: User? = nil, role: String? = nil, createdBy: UUID? = nil, createdDate: Date? = nil, modifiedBy: UUID? = nil, modifiedAt: Date? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.user = user
        self.role = role
        self.createdBy = createdBy
        self.createdDate = createdDate
        self.modifiedBy = modifiedBy
        self.modifiedAt = modifiedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId = "tenant_id"
        case user
        case role
        case createdBy = "created_by"
        case createdDate = "created_date"
        case modifiedBy = "modified_by"
        case modifiedAt = "modified_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(modifiedBy, forKey: .modifiedBy)
        try container.encodeIfPresent(modifiedAt, forKey: .modifiedAt)
    }
}

