//
// TenantConnectionOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TenantConnectionOptions: Codable, JSONEncodable, Hashable {

    public var domainAliases: [String]?

    public init(domainAliases: [String]? = nil) {
        self.domainAliases = domainAliases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domainAliases = "domain_aliases"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(domainAliases, forKey: .domainAliases)
    }
}

