//
// ThreeDSAcsRenderingType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ThreeDSAcsRenderingType: Codable, JSONEncodable, Hashable {

    public var acsInterface: String?
    public var acsUiTemplate: String?

    public init(acsInterface: String? = nil, acsUiTemplate: String? = nil) {
        self.acsInterface = acsInterface
        self.acsUiTemplate = acsUiTemplate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case acsInterface
        case acsUiTemplate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(acsInterface, forKey: .acsInterface)
        try containerEncoder.encodeIfPresent(acsUiTemplate, forKey: .acsUiTemplate)
    }
}

