//
// TokenEnrichments.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenEnrichments: Codable, JSONEncodable, Hashable {

    public var binDetails: BinDetails?

    public init(binDetails: BinDetails? = nil) {
        self.binDetails = binDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case binDetails = "bin_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(binDetails, forKey: .binDetails)
    }
}

