//
// TokenIntent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TokenIntent: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var type: String?
    public var tenantId: UUID?
    public var fingerprint: String?
    public var createdBy: UUID?
    public var createdAt: Date?
    public var expiresAt: Date?
    public var card: CardDetails?
    public var bank: BankDetails?
    public var networkToken: CardDetails?
    public var authentication: JSONValue?
    public var extras: TokenIntentExtras?

    public init(id: String? = nil, type: String? = nil, tenantId: UUID? = nil, fingerprint: String? = nil, createdBy: UUID? = nil, createdAt: Date? = nil, expiresAt: Date? = nil, card: CardDetails? = nil, bank: BankDetails? = nil, networkToken: CardDetails? = nil, authentication: JSONValue? = nil, extras: TokenIntentExtras? = nil) {
        self.id = id
        self.type = type
        self.tenantId = tenantId
        self.fingerprint = fingerprint
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.card = card
        self.bank = bank
        self.networkToken = networkToken
        self.authentication = authentication
        self.extras = extras
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case tenantId = "tenant_id"
        case fingerprint
        case createdBy = "created_by"
        case createdAt = "created_at"
        case expiresAt = "expires_at"
        case card
        case bank
        case networkToken = "network_token"
        case authentication
        case extras = "_extras"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(id, forKey: .id)
        try containerEncoder.encodeIfPresent(type, forKey: .type)
        try containerEncoder.encodeIfPresent(tenantId, forKey: .tenantId)
        try containerEncoder.encodeIfPresent(fingerprint, forKey: .fingerprint)
        try containerEncoder.encodeIfPresent(createdBy, forKey: .createdBy)
        try containerEncoder.encodeIfPresent(createdAt, forKey: .createdAt)
        try containerEncoder.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try containerEncoder.encodeIfPresent(card, forKey: .card)
        try containerEncoder.encodeIfPresent(bank, forKey: .bank)
        try containerEncoder.encodeIfPresent(networkToken, forKey: .networkToken)
        try containerEncoder.encodeIfPresent(authentication, forKey: .authentication)
        try containerEncoder.encodeIfPresent(extras, forKey: .extras)
    }
}

