//
// UpdateTenantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateTenantRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var settings: [String: String]?

    public init(name: String, settings: [String: String]? = nil) {
        self.name = name
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(settings, forKey: .settings)
    }
}

