//
// UpdateTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateTokenRequest: Codable, JSONEncodable, Hashable {

    public var data: AnyCodable?
    public var encryption: EncryptionMetadata?
    public var privacy: UpdatePrivacy?
    public var metadata: [String: String]?
    public var searchIndexes: [String]?
    public var fingerprintExpression: String?
    public var mask: AnyCodable?
    public var expiresAt: String?
    public var deduplicateToken: Bool?
    public var containers: [String]?

    public init(data: AnyCodable? = nil, encryption: EncryptionMetadata? = nil, privacy: UpdatePrivacy? = nil, metadata: [String: String]? = nil, searchIndexes: [String]? = nil, fingerprintExpression: String? = nil, mask: AnyCodable? = nil, expiresAt: String? = nil, deduplicateToken: Bool? = nil, containers: [String]? = nil) {
        self.data = data
        self.encryption = encryption
        self.privacy = privacy
        self.metadata = metadata
        self.searchIndexes = searchIndexes
        self.fingerprintExpression = fingerprintExpression
        self.mask = mask
        self.expiresAt = expiresAt
        self.deduplicateToken = deduplicateToken
        self.containers = containers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case encryption
        case privacy
        case metadata
        case searchIndexes = "search_indexes"
        case fingerprintExpression = "fingerprint_expression"
        case mask
        case expiresAt = "expires_at"
        case deduplicateToken = "deduplicate_token"
        case containers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var containerEncoder = encoder.container(keyedBy: CodingKeys.self)
        try containerEncoder.encodeIfPresent(data, forKey: .data)
        try containerEncoder.encodeIfPresent(encryption, forKey: .encryption)
        try containerEncoder.encodeIfPresent(privacy, forKey: .privacy)
        try containerEncoder.encodeIfPresent(metadata, forKey: .metadata)
        try containerEncoder.encodeIfPresent(searchIndexes, forKey: .searchIndexes)
        try containerEncoder.encodeIfPresent(fingerprintExpression, forKey: .fingerprintExpression)
        try containerEncoder.encodeIfPresent(mask, forKey: .mask)
        try containerEncoder.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try containerEncoder.encodeIfPresent(deduplicateToken, forKey: .deduplicateToken)
        try containerEncoder.encodeIfPresent(containers, forKey: .containers)
    }
}

