//
// UpdatePrivacy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdatePrivacy: Codable, JSONEncodable, Hashable {

    public var impactLevel: String?
    public var restrictionPolicy: String?

    public init(impactLevel: String? = nil, restrictionPolicy: String? = nil) {
        self.impactLevel = impactLevel
        self.restrictionPolicy = restrictionPolicy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case impactLevel = "impact_level"
        case restrictionPolicy = "restriction_policy"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(impactLevel, forKey: .impactLevel)
        try container.encodeIfPresent(restrictionPolicy, forKey: .restrictionPolicy)
    }
}

