name: Semgrep PR Check

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}

jobs:
  pod-linting:
    name: Pod Linting
    runs-on: macOS-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pod Linting
        run: pod lib lint --allow-warnings

  dependency-check-test:
    name: Dependency Check Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Check
        run: |
          docker run -v "/home/runner/work/basistheory-swift/basistheory-swift":"/github/workspace" --workdir "/github/workspace" owasp/dependency-check-action:latest --enableExperimental --project "BasisTheory" --failOnCVSS 1 --scan "Package.swift" --out "/github/workspace/reports"

      - name: Upload Test results
        if: success() || failure()
        uses: actions/upload-artifact@master
        with:
          name: Dependency check report
          path: ${{github.workspace}}/reports

  pr-security-check:
    name: PR Security Check
    uses: Basis-Theory/public-security-workflows/.github/workflows/pr-check.yml@master
    secrets: inherit