name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pod-linting:
    name: Pod Linting
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Pod Linting
        run: pod lib lint --allow-warnings

  dependency-check-test:
    name: Dependency Check Test
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: BasisTheory
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableExperimental
            --failOnCVSS 1
            --scan Package.swift

      - name: Upload Test results
        if: success() || failure()
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
