name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pod-linting:
    name: Pod Linting
    runs-on: macOS-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pod Linting
        run: pod lib lint --allow-warnings

  dependency-check-test:
    name: PR Security Check
    uses: Basis-Theory/security-workflows/.github/workflows/pr-check.yml@master
    secrets: inherit
