name: Semgrep PR Check

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}

jobs:
  pr-security-check:
    name: PR Security Check
    uses: Basis-Theory/public-security-workflows/.github/workflows/pr-check.yml@master
    secrets: inherit
