name: Release

on:
  push:
    branches: [ master ]

jobs:
  tag-repo:
    name: Tag Repo
    runs-on: ubuntu-latest

    outputs:
      releaseType: ${{ steps.tag-version.outputs.release_type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - name: Bump version and push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          tag_prefix: ""

      - name: Commit files
        if: ${{ steps.tag-version.outputs.release_type != '' }}
        run: |
          git config --local user.email "platform@basistheory.com"
          git config --local user.name "github-actions[bot]"

          sed -i "s/\(s.version = \)'[^']*'/\1'${{ steps.tag-version.outputs.new_tag }}'/g" BasisTheory.podspec
          sed -i "s/\(:tag => \)'[^']*'/\1'${{ steps.tag-version.outputs.new_tag }}'/g" BasisTheory.podspec

          echo "${{ steps.tag-version.outputs.changelog }}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md

          git add CHANGELOG.md BasisTheory.podspec
          git commit -m "chore(release): upating podspec and changelog ${{ steps.tag-version.outputs.new_tag }} [skip ci]" || echo "Nothing to update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.tag-version.outputs.release_type != '' }}
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          branch: ${{ github.ref }}

  release-cocoapod:
    name: Release CocoaPod
    runs-on: macOS-latest
    needs:
      - tag-repo

    if: ${{ needs.tag-repo.outputs.releaseType != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Push CocoaPods
        uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.10
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
